### ISSUE TITLE
Update Readme file

### ISSUE THREAD

**Issue by Thuva4** [Thuva4/Algorithms_Example#1]

**Comment by sagarchoudhary96** [comment]
Hey @Thuva4 i would like to help you out :)

**Comment by Thuva4** [comment]
Thank you, I just want to include the list of algorithms in the Readme file. If possible extract the algorithms and the details from wiki page(mentioned in readme file) and add them to readme file.

**Comment by sagarkar10** [comment]
working on it!

**Comment by sagarkar10** [comment]
Need to work on formating the markup and structure the content

**Comment by sagarchoudhary96** [comment]
@Thuva4 I have created the pull Request, please see to it 👍
