### ISSUE TITLE
Create a contributors list in CONTRIBUTING.md

### ISSUE THREAD

**Issue by Thuva4** [Thuva4/Algorithms_Example#224]
* [contributor name](Github Link)

**Comment by deveshd2k** [comment]
Can i go for it?

**Comment by Thuva4** [comment]
Yes :+1:

**Comment by fenilgandhi** [comment]
Is anyone working on this? or shall i complete it ? @Thuva4 @deveshd2k

**Comment by Thuva4** [comment]
@fenilgandhi I did not see any progress. You can work on it. :+1:

**Comment by fenilgandhi** [comment]
I had already started working on it and it is complete now.
https://github.com/Thuva4/Algorithms_Example/pull/260

**Comment by fenilgandhi** [comment]
I guess this issue should be  `closed` now. @Thuva4
