### ISSUE TITLE
Remove special characters such as * in paths and filenames

### ISSUE THREAD

**Issue by IshamMohamed** [Thuva4/Algorithms_Example#241]
Its nearly impossible for Windows users to git clone this repository since it has special characters such as * in paths and filenames. Please remove them.
Please refer this like to get the [list ](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx)of characters to be replaced.

**Comment by maaz93** [comment]
For reference, a full log of the error that appears

```
$ git clone https://github.com/maaz93/Algorithms_Example.git
Cloning into 'Algorithms_Example'...
remote: Counting objects: 1512, done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 1512 (delta 22), reused 36 (delta 8), pack-reused 1462
Receiving objects: 100% (1512/1512), 326.30 KiB | 447.00 KiB/s, done.
Resolving deltas: 100% (552/552), done.
**fatal: cannot create directory at 'A*Search': Invalid argument**
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

**Comment by Thuva4** [comment]
@IshamMohamed @maaz93 Thank you. I will remove those.

**Comment by maaz93** [comment]
After looking through the repo, I think only `Dijkstra's ` is an invalid folder name. Note that it has an extra space at the end of the name and that is causing the problem.

Also, as per @IshamMohamed 's [link](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx), the following characters are invalid

> < (less than)
\> (greater than)
: (colon)
" (double quote)
/ (forward slash)
\ (backslash)
| (vertical bar or pipe)
? (question mark)
\* (asterisk) 

Right now, only the space in `Dijkstra's ` is causing the problem.

**Comment by Thuva4** [comment]
@maaz93 Thank you. I will remove the space.
