### ISSUE TITLE
DepthFirstSearch in Python

### ISSUE THREAD

**Issue by robertmihai26** [Thuva4/Algorithms_Example#248]
Hi. I would like to add the code for the Python version

**Comment by bugov** [comment]
i'll take this

**Comment by robertmihai26** [comment]
I get this when i'm trying to push the branch to origin:

remote: Permission to Thuva4/Algorithms_Example.git denied to robertmihai26.
fatal: unable to access 'https://robertmihai26@github.com/Thuva4/Algorithms_Example.git/': The requested URL returned error: 403

and i can't figure out how to resolve this. Any help?

**Comment by bugov** [comment]
@robertmihai26 I you haven't rights for this. @Thuva4 should do it.

**Comment by Thuva4** [comment]
@robertmihai26 Fork this repo then you can commit your changes to ur forked repo. Then Submit a PR. 
:+1:
